# HCSF - A multilingual CMS and Shopsystem
# Copyright (C) 2014  Marcus Haase - mail@marcus.haase.name
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

email_orderconfirmation_attachment_cancellationform_de: ''
email_orderconfirmation_embed_itemimages: true
email_orderconfirmation_embed_itemimages_glideparams:
  w: 100
email_orderconfirmation_embed_itemimages_method: glide # glide or path
items_orderdirection_default: ASC # ASC or DESC
paypal:
business: paypalseller@domain.tld
url: 'https://www.sandbox.paypal.com/de/cgi-bin/webscr'
auth_token: XXXXXXXXXXXXX
currency_id: EUR
paypal_interactive: true
sofortueberweisung:
user_id: '12345'
project_id: '12345'
currency_id: EUR
paymentmethods:
  - paypal
  - sofortueberweisung
  - nachnahme
  - prepay
interactive_paymentmethods_redirect_immediately: false
shipping_services:
  - DHL
  - UPS
  - DPD
  - GLS
orderamounts:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
show_pricesonlytologgedin: false
custom_order_fields:
  - size
itemdetail_suggestions: 8
itemtext_unsafe_html_whitelist: '' # example: 'td[attr],input[attr1|attr2],form'
itemtext_loose_filtering: false
itemgrouptext_unsafe_html_whitelist: '' # example: 'td[attr],input[attr1|attr2],form'
itemgrouptext_loose_filtering: false
minimumorderamountnet: 0
reducedorderamountnet1: 0
reducedorderamountnet2: 0
reducedorderamountfee1: 0
reducedorderamountfee2: 0
minimumamountforfreeshipping: 0
waehrungssymbol: '&euro;'
shippingcoststandardrate: 6.713
shippingcosts:
  -
    cost: 3.35
    countries:
    DE: DE
  -
    cost: 4.19
    countries:
      BE: BE
      FR: FR
      LI: LI
      LU: LU
      MC: MC
      NL: NL
      CH: CH
      AT: AT
      GG: GG
      JE: JE
      AX: AX
      DK: DK
      EE: EE
      FI: FI
      FO: FO
      IE: IE
      IS: IS
      IM: IM
      LV: LV
      LT: LT
      'NO': 'NO'
      SE: SE
      SJ: SJ
      GB: GB
      BW: BW
      LS: LS
      NA: NA
      SZ: SZ
      ZA: ZA
      BY: BY
      BG: BG
      PL: PL
      MD: MD
      RO: RO
      RU: RU
      SK: SK
      CZ: CZ
      UA: UA
      HU: HU
      AL: AL
      AD: AD
      BA: BA
      GI: GI
      GR: GR
      IT: IT
      HR: HR
      MT: MT
      MK: MK
      ME: ME
      PT: PT
      SM: SM
      RS: RS
      CS: CS
      SI: SI
      ES: ES
      VA: VA
rebate_groups:
  '01':
    grosskunde: 10
    wiederverkaeufer: 15
  '02':
    grosskunde: 7
    wiederverkaeufer: 11
vat_disable: true
vat:
  full: 19
  reduced: 7
directory_images_items: items
directory_images_items_email: 90
